name: main

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: pm2 delete willishakespeare-portfolio-main
      - run: rm -rf ~/runers/Willishakespeare/projects/Portfolio/main/
      - run: cp -r ~/runers/Willishakespeare/projects/Portfolio/Portfolio/ ~/runers/Willishakespeare/projects/Portfolio/main/
      - run: cd ~/runers/Willishakespeare/projects/Portfolio/main/
      - run: pm2 start --name willishakespeare-portfolio-main yarn -- start --port 3100
